### ISSUE TITLE
(Android) - Crash when running app with CheckJNI

### ISSUE THREAD

**Issue by jdrider** [thomsonreuters/TRCharts#2]
The following crash occurs intermittedly when running an app in debug mode so that [CheckJNI](http://android-developers.blogspot.com/2011/07/debugging-android-jni-with-checkjni.html) is enabled.  This crash does not appear when the app is run in release mode, only when the extra checks provided by CheckJNI are being used.

```
A/art: sart/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: thread Thread[8,tid=907,Native,Thread*=0xb8e098d0,peer=0x22c072c0,"FinalizerDaemon"] using JNIEnv* from thread Thread[1,tid=897,Runnable,Thread*=0xb8da9ec0,peer=0x865a9000,"main"]
A/art: sart/runtime/check_jni.cc:65]     in call to DeleteGlobalRef
A/art: sart/runtime/check_jni.cc:65]     from void com.thomsonreuters.corptech.charts.LineSeries.nativeDestroy(long)
A/art: sart/runtime/check_jni.cc:65] "FinalizerDaemon" daemon prio=5 tid=8 Runnable
A/art: sart/runtime/check_jni.cc:65]   | group="system" sCount=0 dsCount=0 obj=0x22c072c0 self=0xb8e098d0
A/art: sart/runtime/check_jni.cc:65]   | sysTid=907 nice=0 cgrp=apps/bg_non_interactive sched=0/0 handle=0xb8e0e880
A/art: sart/runtime/check_jni.cc:65]   | state=R schedstat=( 679393621 232336613 1678 ) utm=47 stm=20 core=3 HZ=100
A/art: sart/runtime/check_jni.cc:65]   | stack=0xb450d000-0xb450f000 stackSize=1036KB
A/art: sart/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
A/art: sart/runtime/check_jni.cc:65]   native: #00 pc 00004640  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
A/art: sart/runtime/check_jni.cc:65]   native: #01 pc 00002e8d  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
A/art: sart/runtime/check_jni.cc:65]   native: #02 pc 00248961  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+68)
A/art: sart/runtime/check_jni.cc:65]   native: #03 pc 0022d697  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+146)
A/art: sart/runtime/check_jni.cc:65]   native: #04 pc 000b18db  /system/lib/libart.so (art::JniAbort(char const*, char const*)+582)
A/art: sart/runtime/check_jni.cc:65]   native: #05 pc 000b2015  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
A/art: sart/runtime/check_jni.cc:65]   native: #06 pc 000b508d  /system/lib/libart.so (art::ScopedCheck::ScopedCheck(_JNIEnv*, int, char const*)+1132)
A/art: sart/runtime/check_jni.cc:65]   native: #07 pc 000b6463  /system/lib/libart.so (art::CheckJNI::DeleteGlobalRef(_JNIEnv*, _jobject*)+50)
A/art: sart/runtime/check_jni.cc:65]   native: #08 pc 00246754  /data/app/app-1/lib/arm/libTRChartsJNI.so (_JNIEnv::DeleteGlobalRef(_jobject*)+40)
A/art: sart/runtime/check_jni.cc:65]   native: #09 pc 002d64f8  /data/app/app-1/lib/arm/libTRChartsJNI.so (TRChartsJNI::ContinuousDataSourceInterfaceMarshaller<Charts::ScalarDatum>::marshall(_JNIEnv*, _jobject* const&) const::'lambda'(Charts::ContinuousDataSource<Charts::ScalarDatum>*)::operator()(Charts::ContinuousDataSource<Charts::ScalarDatum>*) const+80)
A/art: sart/runtime/check_jni.cc:65]   native: #10 pc 002e9498  /data/app/app-1/lib/arm/libTRChartsJNI.so (std::_Sp_counted_deleter<TRChartsJNI::ContinuousDataSourceInterfaceMarshaller<Charts::ScalarDatum>::Proxy*, TRChartsJNI::ContinuousDataSourceInterfaceMarshaller<Charts::ScalarDatum>::marshall(_JNIEnv*, _jobject* const&) const::'lambda'(Charts::ContinuousDataSource<Charts::ScalarDatum>*), std::allocator<int>, (__gnu_cxx::_Lock_policy)2>::_M_dispose()+40)
A/art: sart/runtime/check_jni.cc:65]   native: #11 pc 00247cd4  /data/app/app-1/lib/arm/libTRChartsJNI.so (std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release()+84)
A/art: sart/runtime/check_jni.cc:65]   native: #12 pc 002477cc  /data/app/app-1/lib/arm/libTRChartsJNI.so (std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count()+44)
A/art: sart/runtime/check_jni.cc:65]   native: #13 pc 0024d5fc  /data/app/app-1/lib/arm/libTRChartsJNI.so (std::__shared_ptr<Charts::ContinuousDataSource<Charts::ScalarDatum>, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr()+28)
A/art: sart/runtime/check_jni.cc:65]   native: #14 pc 0024d628  /data/app/app-1/lib/arm/libTRChartsJNI.so (std::shared_ptr<Charts::ContinuousDataSource<Charts::ScalarDatum> >::~shared_ptr()+24)
A/art: sart/runtime/check_jni.cc:65]   native: #15 pc 003564c4  /data/app/app-1/lib/arm/libTRChartsJNI.so (Charts::ContinuousSeries<Charts::ScalarDatum>::~ContinuousSeries()+112)
A/art: sart/runtime/check_jni.cc:65]   native: #16 pc 003560e0  /data/app/app-1/lib/arm/libTRChartsJNI.so (Charts::GeneratedLineSeries::~GeneratedLineSeries()+92)
A/art: sart/runtime/check_jni.cc:65]   native: #17 pc 00342574  /data/app/app-1/lib/arm/libTRChartsJNI.so (Charts::LineSeries::~LineSeries()+156)
A/art: sart/runtime/check_jni.cc:65]   native: #18 pc 003425c8  /data/app/app-1/lib/arm/libTRChartsJNI.so (Charts::LineSeries::~LineSeries()+20)
A/art: sart/runtime/check_jni.cc:65]   native: #19 pc 002ac06c  /data/app/app-1/lib/arm/libTRChartsJNI.so (TRChartsJNI::Handle::~Handle()+64)
A/art: sart/runtime/check_jni.cc:65]   native: #20 pc 00286b7c  /data/app/app-1/lib/arm/libTRChartsJNI.so (Java_com_thomsonreuters_corptech_charts_LineSeries_nativeDestroy+136)
A/art: sart/runtime/check_jni.cc:65]   native: #21 pc 00203a83  /data/dalvik-cache/arm/data@app@app-1@base.apk@classes.dex (Java_com_thomsonreuters_corptech_charts_LineSeries_nativeDestroy__J+90)
A/art: sart/runtime/check_jni.cc:65]   at com.thomsonreuters.corptech.charts.LineSeries.nativeDestroy(Native method)
A/art: sart/runtime/check_jni.cc:65]   at com.thomsonreuters.corptech.charts.LineSeries.onFinalize(LineSeries.java:156)
A/art: sart/runtime/check_jni.cc:65]   at com.thomsonreuters.corptech.charts.BaseObject.finalize(BaseObject.java:72)
A/art: sart/runtime/check_jni.cc:65]   at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:209)
A/art: sart/runtime/check_jni.cc:65]   at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:192)
A/art: sart/runtime/check_jni.cc:65]   at java.lang.Thread.run(Thread.java:818)
```

Environment: Android 5.0.2 (ART Runtime)

Steps To Reproduce
1. Run app in debug mode with rendered content in a TRChartsView on an Android 5.0 device.
2. After content has rendered, send the app to the background.
3. May see message "Dependent disposable destroyed after render context destroyed" printed multiple times to the console.
4. App will crash with the above stack trace.

**Comment by FranciscoE-Hudl** [comment]
Have you modified the base code, or is this error happening on your own app?

If that is the case, can you please check that all your interactions with the chart are done on the main thread? The problem seems to happen when one of the objects falls out of scope in the wrong thread.

**Comment by jdrider** [comment]
This error is happening in my own app.  I verified that all of my calls on the chart are done on the main thread but am still seeing this error in debug builds.  I'll see if I can modify the sandbox app to reproduce this error.
